site_name: José André Rabelo | Desafio Técnico - V360
theme:
  name: "material"
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    scheme: default
    primary: white
    accent: orange
  font:
    text: "Roboto"
    code: "Roboto Mono"
  favicon: assets/favicon.ico
  logo: assets/logo.ico

nav:
  - Descrição do Desafio: index.md
  - Requisitos Levantados:
    - Visão de Produto: requisitos/visao-de-produto.md
    - Requisitos Funcionais: requisitos/requisitos-funcionais.md
    - Requisitos Não Funcionais: requisitos/requisitos-nao-funcionais.md
  - Documentação Funcional:
    - Anexo: documentacao-funcional/documentacao-anexo.md
  - Macrocronograma de Implantação: macrocronograma/macrocronograma-implantacao.md