site_name: José André Rabelo | Desafio Técnico - V360
theme:
  name: "material"
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    scheme: default
    primary: orange
    accent: purple
  extra_css:
    - stylesheets/extra.css
  font:
    text: "Roboto"
    code: "Roboto Mono"

nav:
  - Descrição do Desafio: index.md
  - Requisitos Levantados:
    - Visão de Produto: requisitos/visao-de-produto.md
    - Requisitos Funcionais: requisitos/requisitos-funcionais.md
    - Personas: requisitos/personas.md
    - Requisitos Não Funcionais: requisitos/requisitos-nao-funcionais.md
  - Macrocronograma de Implantação:
    - Backlog: macrocronograma/backlog.md
    - Macrocronograma: macrocronograma/macrocronograma-implantacao.md
